sveltejs/site-kit

package-lock.json
package.json
test/unit/slug.js
utils/slug.js

Also set licence to MIT as per Svelte repo (where this code came from)

Utils, slug: export constants, fix tests

---

components/Docs.svelte
components/Nav.svelte

Just add some props which allow to set visible text labels for better i18n support.
Currently, I need it for russian sites.

changes for i18n support

---

base.css

adjust toggle switch head position

---

utils/markdown.js

Adds diff syntax to langs for the TS blogpost.

add diff to langs

---

components/Docs.svelte
components/GuideContents.svelte

Use `dir` prop for navigation and anchor

---

components/Docs.svelte

Fixes [#5222](https://github.com/sveltejs/svelte/issues/5222)

Fix anchor alignment for h4 elements

---

package-lock.json
package.json
utils/markdown.js

This will allow us to merge https://github.com/sveltejs/svelte/pull/6206 in an effort to migrate the svelte.dev site to the new sveltejs/sites

Support quoted frontmatter

---

packages/site-kit/CHANGELOG.md
packages/site-kit/package.json
packages/site-kit/src/lib/components/Icon.svelte
packages/site-kit/src/lib/components/Nav.svelte
packages/site-kit/src/lib/components/NavItem.svelte
packages/site-kit/src/lib/styles/base.css
packages/site-kit/src/lib/styles/text.css

the last commit caused some wacky errors

undo last change

---

.changeset/dull-shoes-arrive.md
.github/workflows/release.yml
package.json
packages/site-kit/package.json
pnpm-lock.yaml

Hoping this fixes the root dir being published issue

fix: Changeset publishing

---

.changeset/shaggy-sheep-fetch.md
.prettierrc
packages/site-kit/src/lib/actions/focus.js
packages/site-kit/src/lib/search/Search.svelte
packages/site-kit/src/lib/search/SearchBox.svelte
packages/site-kit/src/lib/search/SearchResultList.svelte
packages/site-kit/src/lib/search/SearchResults.svelte
packages/site-kit/src/lib/search/search-worker.js
packages/site-kit/src/lib/search/search.js
packages/site-kit/src/lib/search/stores.js
packages/site-kit/src/lib/search/types.d.ts

extracted from kit.svelte.dev, svelte.dev sites branch seems to use the same, so should be safe for reuse

feat: add actions and search for reuse

---

.changeset/dull-toes-switch.md
packages/site-kit/src/lib/components/Nav.svelte
packages/site-kit/src/lib/components/NavItem.svelte
packages/site-kit/src/lib/components/Separator.svelte
packages/site-kit/src/lib/components/Shell.svelte

Should make reuse easier across Svelte repos

feat: add shell component and adjust related components

---

.changeset/shiny-balloons-jump.md
packages/site-kit/package.json

should help for Vite auto-noExternal etc

fix: add svelte and sveltekit as peerDeps

---

.changeset/proud-adults-mix.md
packages/site-kit/package.json
packages/site-kit/src/lib/styles/tokens.css
pnpm-lock.yaml

Makes the dark mode diff styles slightly easier on eyes

fix: Dark mode diff style change

---

.changeset/wild-bulldogs-tie.md
packages/site-kit/src/lib/components/TSToggle.svelte
packages/site-kit/src/lib/components/ToggleButton.svelte
packages/site-kit/src/lib/components/index.js
packages/site-kit/src/lib/theme/store.js

Also changes `sveltekit:theme` to `svelte:theme`

feat: Move ts-toggle to site-kit

---

.changeset/strange-snakes-warn.md
packages/site-kit/src/lib/styles/text.css
packages/site-kit/src/lib/styles/tokens.css

Adds a tiny label to blockquotes, allows deprecated blockquote

feat: Add deprecated styles for blockquotes

---

.changeset/three-spoons-march.md
packages/site-kit/src/lib/styles/text.css

fix: link theming

---

packages/site-kit/src/lib/components/Blurb.svelte
packages/site-kit/src/lib/components/TryTerminal.svelte

Monochrome terminal chrome

---

.changeset/hip-terms-promise.md
packages/site-kit/src/lib/nav/Nav.svelte

oops, not sure how that happened

---

.changeset/forty-seals-check.md
packages/site-kit/src/lib/docs/DocsOnThisPage.svelte
packages/site-kit/src/lib/markdown/renderer.js

This makes renderer logic generate kit-friendly slugs

fix(renderer): Fallthrough headings like Kit

---

.changeset/cold-rules-cover.md
packages/site-kit/src/lib/search/SearchBox.svelte

reset search query when opening modal

---

.changeset/pink-llamas-explode.md
packages/site-kit/src/lib/markdown/renderer.js

On my macbook, brings down cache files read time from 9ms to 1ms

chore: 10x faster cache reads

---

.changeset/nasty-keys-grow.md
packages/site-kit/src/lib/styles/tokens.css

based off @vedam's suggestion. I didn't have time to update everything. just tweaking the bare minimum to address accessibility issues

fix: tweak background color to address contrast issues

---

.changeset/rotten-adults-move.md
package.json
packages/site-kit/package.json
packages/site-kit/src/lib/components/Banners.svelte
packages/site-kit/src/lib/docs/TSToggle.svelte
packages/site-kit/src/lib/stores/search.js
packages/site-kit/src/lib/stores/theme.js
pnpm-lock.yaml

chore: Bump deps

---

.changeset/calm-nails-ring.md
packages/site-kit/src/lib/home/Footer.svelte

Just a quick small change: Updating the copyright year from 2023 to 2024

Updated the copyright year
