sveltejs/site-kit

components/Docs.svelte

Adds a prop `project` to the Docs component so that the 'edit this page' button works for other projects besides svelte. Has a default value `svelte` so it doesn't break things when merged.
This prop can be used on the sapper docs `site/src/routes/docs/index.svelte` like so...
https://github.com/sveltejs/sapper/blob/75afc691f4b47a3d9d1f8c933a5efeb218ceaa51/site/src/routes/docs/index.svelte#L22
```
<Docs {sections} project='sapper'/>
```
Question for maintainer:
Just one consideration, would it make it more clear to use the word `repo` or `repository` instead of `project`? I can update the PR if that's the case.

Add prop to change repo for each sveltejs project

---

utils/markdown.js

Required to add svelte syntax highlighting to the svelte site.
We could change html to svelte as well, the svelte highlighter supports all html syntax.

Change languages.

---

utils/markdown.js

add  rel="noopener noreferrer" to links for security
lighthouse caught this, i assume you know what it is already but let me know if a further justificaiton is needed

add  rel="noopener noreferrer" to links for security

---

base.css

To be able to navigate with the keyboard, you need focus styles. Removing focus styles while not providing an alternative is not good for accessibility.
Signed-off-by: Wolfr <johan.ronsse@gmail.com>

Don't remove the outline on focus

---

components/Blurb.svelte

A white border on the bottom apear when hovering the link. This cause some displacement.
I solved it by adding a `border: none;` in the css. Every other links were already doing this, but this one has probably been forgotten.

Fixing border of "Learn ..." button on home page

---

components/Blurb.svelte

In the `Blurb` cards, the right arrow next to 'learn more' was getting clipped due to its positioning. Since the icon is 24px by 24px, changing the width and height fixed the issue.
Before:
After:

fixing: right arrow getting clipped next to 'learn more'

---

components/NavItem.svelte

> Links do not have a discernible name
is being reported by _Google Lighthouse_ for the icon navigation links within the header on [svelte.dev](https://svelte.dev/), the ones shown on this screenshot:
This is most likely related to that [/sveltejs/svelte/blob/master/site/src/routes/_layout.svelte](https://github.com/sveltejs/svelte/blob/master/site/src/routes/_layout.svelte) includes `title` property declarations for `site-kit`'s `NavItem` component, but those aren't included in the component itself.
Same for problem related to [sapper.svelte.dev](https://sapper.svelte.dev/): https://github.com/sveltejs/sapper/blob/master/site/src/routes/_layout.svelte

fix(NavItem): added missing title property

---

base.css

Fixed the CSS issue on iOS web browsers where the input knob was off center and there was a system style behind the knob too.
To Test:
- `npm link` the PR in site-kit to `svlete` repo in `site` folder
- Run an emulator and then go to localhost. (can use Xcode with a sample iOS app)
If you want to have access to the developer console within safari iOS emulator:
- Go to safari develop tab --> select simulator.

fix: input css on iOS

---

components/Docs.svelte

Because always return `window.scrollY` return `0`.
Alternatively, use `element.getBoundingClientRect().top` to determine
active section.
Relative Issues: #20.

fix #20 strange menu scrollbar behaivor

---

components/NavItem.svelte

This allows linking to endpoints and thereby solves the broken link to https://svelte.dev/chat from the header on svelte.dev.

Set rel="external" on external NavItem

---

packages/site-kit/src/lib/styles/text.css

taking another crack at blockquote styles. i don't hate this one. it uses an existing theme colour, it's easily distinguishable from `<pre>` blocks etc, it can accommodate any content without a11y problems because it has a white background, etc

blockquote style

---

.changeset/seven-rocks-tap.md
packages/site-kit/src/lib/components/Shell.svelte
packages/site-kit/src/lib/search/SearchBox.svelte

package is not actually built, so no "resolve $lib alias" step is happening

fix: remove $lib aliases for now

---

packages/site-kit/src/lib/components/Icons.svelte

punch holes in chat icon

---

.changeset/curvy-trainers-tan.md
packages/site-kit/src/lib/components/Nav.svelte

.svelte.dev isn't hidden anymore on small screens

fix: Don't hide nav home title on small screen

---

.changeset/seven-flies-worry.md
packages/site-kit/src/lib/components/Nav.svelte
packages/site-kit/src/lib/components/ThemeToggle.svelte
packages/site-kit/src/lib/components/ToggleButton.svelte

Noticed a few a11y issues on the SvelteKit site - this PR fixes them.
It isn't valid HTML to have a `<div>` in a `<ul>`. I refactored the Nav component so that was no longer necessary. It required refactoring the CSS a bit as well but everything seems to work in my local SvelteKit site.
The component was using a `<label>` around a `<button>`, which may not work in all browsers - at least, Axe was throwing a "Ensure buttons have discernible text" error. I refactored to use aria-label instead. I also swapped out `role="switch"` for `aria-pressed` to be consistent with how the TS toggle is implemented. `role="switch"` isn't wrong, but `aria-pressed` is slightly more appropriate for or use case. For more info, see rationale in https://github.com/sveltejs/kit/pull/7928.
While working on this, …

Various a11y fixes

---

.changeset/mean-spies-worry.md
packages/site-kit/src/lib/search/SearchBox.svelte

I came across a issue about IME, in the SearchBox.
For more information about IME and KeyboardEvent, please see this article:
- https://developer.squareup.com/blog/understanding-composition-browser-events/
I understand that this PR is not necessary for the official English site, but I believe this will be helpful for other language site in the future, and should not affect users who do not use an IME.

chore: add IME support for SearchBox

---

.changeset/unlucky-cougars-trade.md
packages/site-kit/src/lib/nav/Menu.svelte

Fixed by waiting for NavContextMenu to be created, with `await tick()`;

fix: Clicking on context menu arrow throw erros

---

.changeset/tricky-swans-knock.md
packages/site-kit/src/lib/styles/text.css

Links in blockquote weren't being colored or underlined. This fixes that

fix: link style in blockquote

---

packages/site-kit/src/lib/actions/focus.js
packages/site-kit/src/lib/docs/DocsOnThisPage.svelte
packages/site-kit/src/lib/nav/Menu.svelte
packages/site-kit/src/lib/nav/Nav.svelte

This PR is a bunch of improvements for a11y and the new site. Summary of changes:
Focus wasn't being set when swapping between submenus (e.g. the main menu and the docs sub menu) so it was getting lost, since the outroing menu becomes inert. I manually focused the first link in whatever menu was becoming available. This had to happen in a transitionend event; otherwise, focus moved too soon and it caused some animation glitches.
So that this focus management also works when reduced motion is enabled, instead of disabling transitions completely for reduced motion I set a very low transition duration.
The mobile nav could receive keyboard focus but not show, since that's triggered on scroll. I updated the CSS to also show the nav if focus is inside it.
It's invalid to nest interactive …

Improve a11y of new site design

---

.changeset/rare-crabs-bake.md
packages/site-kit/src/lib/components/Icons.svelte

This adds two new icons (from [feather icons](https://feathericons.com/?query=chevron), since it seems we've gotten icons from there before). It's needed for some work I'm doing for https://github.com/sveltejs/sites/issues/494 (see also https://github.com/sveltejs/svelte/pull/8831)

Add chevron-up and chevron-down icons

---

.changeset/pretty-eagles-march.md
packages/site-kit/src/lib/docs/DocsOnThisPage.svelte

The existing implementation of the "On this page" nav still attached the click handler on the desktop view, even though the element was no longer a toggle. This meant you could still click it and the screen would dim, without any way to un-dim the screen.
This PR makes it so we only render a button (and attach the click handler) on mobile screen widths. It also improves semantics by reinstating the "On this page" h2, allowing assistive tech users to skip to it via heading shortcuts.
Swapping between the button and static text is done with CSS to avoid FOUC.

fix: prevent triggering "On this page" overlay on desktop

---

.changeset/yellow-islands-pump.md
packages/site-kit/src/lib/nav/Nav.svelte

Firefox for Android occasionally emits multiple scroll events with the same `scrollTop` integer value towards the end of an inertia scroll, which causes the Nav to flicker between visible states. This fixes it by keeping the visible state the same if `scrollTop` is unchanged.

fix: prevent Nav flickering on mobile

---

.changeset/tiny-suns-tease.md
packages/site-kit/src/lib/docs/DocsOnThisPage.svelte

in the https://svelte.dev/docs/accessibility-warnings when the aside has long content, it will have 2 scrollbars visible when scrolling down: 1 for the page content, 1 for the aside.
this PR hides the scrollbar in aside

feat: hide scrollbar in aside

---

.changeset/tasty-parents-chew.md
packages/site-kit/src/lib/search/SearchBox.svelte

I could not test it (got `npm link` issues), but this seems right.

fix: forward searchbox no-result slot

---

.changeset/strange-clocks-join.md
packages/site-kit/src/lib/search/SearchBox.svelte

I am so sorry for the multiple PRs on this topic, this should have been done correctly from the start in #192 ...
I still could not test this properly, I'm still facing issues with linking my local `site-kit` package, it complains with `Cannot find module '@sveltejs/site-kit/components'`, probably because of the packaged architecture... maybe someone knows how i can make the linking working.

fix: searchbox no-results slot

---

packages/site-kit/src/lib/styles/tokens.css

didn't realized this value was duplicated and only updated it in one place in https://github.com/sveltejs/site-kit/pull/206

fix: update background color in other location

---

.changeset/long-weeks-turn.md
packages/site-kit/src/lib/nav/Menu.svelte
packages/site-kit/src/lib/nav/index.js

This requires converting many variables to stores, to ensure they work in script context module

feat: export open_nav function

---

.changeset/healthy-badgers-flash.md
packages/site-kit/src/lib/actions/copy-code-descendants.js

I thought that I didn’t want to delete deleted line manually.
Without this PR:
https://github.com/sveltejs/site-kit/assets/19153718/3c6452d8-f563-407b-b328-33997dc8414d
With this PR:
https://github.com/sveltejs/site-kit/assets/19153718/c38c6bac-6299-4819-b21c-2ec26692bd7d
(Oh I'm not sure why video preview doesn't exist...)
And can we cut a new release after merging this PR?
I want to apply this change to the Svelte5 preview site.

fix: Do not copy deleted lines

---

.changeset/cuddly-mails-sit.md
packages/site-kit/src/lib/nav/Nav.svelte

closes #246 
Text will now be center aligened:

fix: home link vertical alignment

---

.changeset/clean-wombats-work.md
packages/site-kit/src/lib/components/Banner.svelte
packages/site-kit/src/lib/components/Banners.svelte
packages/site-kit/src/lib/components/index.js

This binds the banner to start and end times. it assumes the user knows what they are doing and they wont set start > end 😅
This allows having multiple banners in the code, all with their time. For eg, we can have 2 banners in the site code, one for "Join us for svelte summit" and one for "Svelte Summit talks are out now". They both will be bound to their time, hence we can show them subsequently without needing a subsequent PR at the right time. 
This also allows us to set and forget them completely, until the next event comes up. This will avoid the awkward situation where the banner says "Join us on November 12" and the current date is December 1

feat: Time-bound banner

---

.changeset/curly-lemons-care.md
packages/site-kit/src/lib/components/Banner.svelte
packages/site-kit/src/lib/components/Banners.svelte
packages/site-kit/src/lib/components/index.js

Refactors Banners component to do the gruntwork, Banner is now responsible only for changing the local persistence.
Added in error in case any two banners have overlapping timeframes. This will fail the build completely
Also exposes a new method: `defineBanner`

chore: Refactor banner, stricter

---

.changeset/odd-waves-glow.md
packages/site-kit/src/lib/markdown/utils.js

fixes https://github.com/sveltejs/svelte/issues/11100

fix: url tokenizer to not treat package version string as email

---

.changeset/olive-eggs-develop.md
packages/site-kit/src/lib/docs/DocsCopyCodeButton.svelte

The copy code button currently has no accessible name. This fixes this by adding a hidden span

fix: add accessible text to copy code button

---

package.json
pnpm-lock.yaml

Contrary to my previous assumption, none of the svelte repos are using pnpm v9, so switching back to v8 for now

fix: pnpm 8

---

.changeset/chilly-lizards-sip.md
packages/site-kit/src/lib/home/Footer.svelte
packages/site-kit/src/lib/home/TryTerminal.svelte
packages/site-kit/src/lib/nav/Menu.svelte
packages/site-kit/src/lib/nav/NavContextMenu.svelte
packages/site-kit/src/lib/nav/PreloadingIndicator.svelte

not quite sure how these got missed in #288

fix: remove more self-closing tags
